# Generated by Django 5.2.3 on 2025-07-07 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.TextField(blank=True, help_text='Office address to display')),
                ('phone_number', models.CharField(blank=True, help_text='Main contact phone', max_length=20)),
                ('email_address', models.EmailField(blank=True, help_text='Main contact email', max_length=254)),
                ('business_hours', models.TextField(blank=True, help_text='Business hours information')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('auto_response_enabled', models.BooleanField(default=True)),
                ('auto_response_message', models.TextField(default='Thank you for contacting us! We have received your message and will get back to you within 24-48 hours.', help_text='Automatic response message sent to users')),
                ('admin_notification_enabled', models.BooleanField(default=True)),
                ('admin_notification_emails', models.TextField(blank=True, help_text='Comma-separated list of admin emails to notify on new messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person contacting', max_length=100)),
                ('email', models.EmailField(help_text='Valid email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('company', models.CharField(blank=True, help_text='Optional company name', max_length=100, null=True)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('business', 'Business Partnership'), ('feedback', 'Feedback'), ('bug_report', 'Bug Report'), ('feature_request', 'Feature Request'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField(help_text='Detailed message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of sender', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent', null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_con_status_402fcf_idx'), models.Index(fields=['subject', 'created_at'], name='contact_con_subject_44866e_idx'), models.Index(fields=['is_read', 'created_at'], name='contact_con_is_read_252076_idx')],
            },
        ),
    ]
