# Generated by Django 5.2.3 on 2025-07-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='availability_info',
            field=models.TextField(blank=True, help_text='When the community is most active or available'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='community_description',
            field=models.TextField(blank=True, help_text='Description of the community'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Main contact email for the community', max_length=254),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='discord_server',
            field=models.URLField(blank=True, help_text='Discord server invite link', null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub organization/repository', null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='website_url',
            field=models.URLField(blank=True, help_text='Main community website', null=True),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel', null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn page', null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X account', null=True),
        ),
    ]
