# Generated by Django 5.2.3 on 2025-07-05 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lab_url', models.URLField()),
                ('objectives', models.TextField()),
                ('difficulty_level', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('prize', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(help_text='Time spent in minutes')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('is_ok', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_labs', to='labs.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_labs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
