# Generated by Django 5.2.3 on 2025-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='cooldown_minutes',
            field=models.IntegerField(default=0, help_text='Cooldown time in minutes before user can retake the lab'),
        ),
        migrations.AddField(
            model_name='lab',
            name='external_lab_id',
            field=models.CharField(blank=True, help_text='ID used by the external exam system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='max_score',
            field=models.IntegerField(default=100, help_text='Maximum score possible for this lab'),
        ),
        migrations.AddField(
            model_name='lab',
            name='reward_points',
            field=models.IntegerField(default=0, help_text='Points rewarded for passing this lab, set by external system'),
        ),
        migrations.AddField(
            model_name='userlab',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, help_text='User cannot retake until this time', null=True),
        ),
        migrations.AddField(
            model_name='userlab',
            name='external_attempt_id',
            field=models.CharField(blank=True, help_text='Attempt ID from external system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlab',
            name='reward_points_earned',
            field=models.IntegerField(default=0, help_text='Points earned for this attempt'),
        ),
    ]
