# Generated by Django 5.2.3 on 2025-07-01 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['title'], name='documentati_title_83db30_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['category'], name='documentati_categor_fad068_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['is_active'], name='documentati_is_acti_d898bd_idx'),
        ),
    ]
