# Generated by Django 5.2.3 on 2025-07-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0002_documentation_documentati_title_83db30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='main_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
