# Generated by Django 5.2.3 on 2025-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentations', '0003_alter_documentation_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='category',
            field=models.CharField(choices=[('learning_path', 'Learning Path'), ('solution', 'Solution'), ('general_post', 'General Post')], max_length=100),
        ),
    ]
