# Generated by Django 5.2.3 on 2025-07-05 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('is_pro', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('badge_pic', models.ImageField(blank=True, null=True, upload_to='certification_badges/')),
                ('test_url', models.CharField(max_length=500)),
                ('required_completion', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('recurring_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('completion', models.FloatField(blank=True, null=True)),
                ('last_attend', models.DateTimeField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certifications', to='certifications.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['name'], name='certificati_name_b61e55_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['category'], name='certificati_categor_1f536b_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['is_active'], name='certificati_is_acti_c2faef_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['user'], name='certificati_user_id_514abb_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['certification'], name='certificati_certifi_04abf8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['done_at'], name='certificati_done_at_213809_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercertification',
            unique_together={('user', 'certification')},
        ),
    ]
