# Generated by Django 5.2.3 on 2025-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='in_lights_date',
            field=models.DateTimeField(blank=True, help_text='Date when job is highlighted by admin', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='message',
            field=models.TextField(blank=True, help_text='Message from applicant to employer', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='pending', help_text='Application status: pending, accepted, rejected, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='meta_data',
            field=models.JSONField(blank=True, help_text='Auto-filled with user bio and other details at apply time', null=True),
        ),
    ]
