# Generated by Django 5.2.3 on 2025-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_lights_date',
            field=models.DateTimeField(blank=True, help_text='Date when event is highlighted by admin', null=True),
        ),
    ]
