# Generated by Django 5.2.3 on 2025-07-06 13:33

from django.db import migrations
from django.utils.text import slugify


def populate_event_slugs(apps, schema_editor):
    """Populate slugs for existing events"""
    Event = apps.get_model('events', 'Event')

    for event in Event.objects.all():
        if event.title:
            base_slug = slugify(event.title)
            if not base_slug:
                base_slug = f"event-{event.id}"
        else:
            base_slug = f"event-{event.id}"

        # Ensure uniqueness
        slug = base_slug
        counter = 1
        while Event.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        event.slug = slug
        event.save()


def reverse_populate_event_slugs(apps, schema_editor):
    """Reverse operation - clear slugs"""
    Event = apps.get_model('events', 'Event')
    Event.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcategory_eventview_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_event_slugs, reverse_populate_event_slugs),
    ]
